/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Yu' at '15/09/13 21:46' with Gradle 2.5-rc-2
 *
 * @author Yu, @date 15/09/13 21:46
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
